HOSTS:
  ubuntu-1404-x64:
    roles:
      - agent
      - default
    platform: ubuntu-1404-amd64
    box: puppetlabs/ubuntu-14.04-64-nocm
    hypervisor: vagrant
CONFIG:
  log_level: verbose
  type: foss
